### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ChezFre**
This should make it a bit easier for novice AngularJS users, like myself, to get started with angular-dropzone.

### CODE REVIEW

**Comment by sudopopco** [comment]
Thanks for the write up. This seems to be in the right direction but this directive still doesn't work for me. I seem to be getting a conflict with the Dropzone object when I include ngDropzone as a dependency. I get a "Dropzone is not a constructor" error. If i jump into the console and try to look at Dropzone and instantiate it, i get Dropzone is already attached. I'm kinda lost here. It works fine outside of angular. :/

**Comment by ChezFre** [comment]
I didn't have this issue myself, but I just created a testcase and had it happen there as well. It's because Dropzone automatically creates new instances while the directive creates it as well.

This can be solved by adding an id to the element you're trying to create a Dropzone for and then adding `Dropzone.options.uploadDemo = false;` Where 'uploadDemo' is the Camel Cased version of your id.  Or you can add `Dropzone.autoDiscover = false;` to the Directive directly under the try/catch.
(see the autoDiscover section of http://www.dropzonejs.com/).

[dropzone.zip](https://github.com/sandbochs/angular-dropzone/files/109427/dropzone.zip)

**Comment by sudopopco** [comment]
Thanks, that helped a lot. The "not a constructor" error happened to be an issue with the way gulp was ordering dependencies during the build.

**Comment by sandbochs** [comment]
@ChezFre Thanks for updating the README!

**Pull request merged**
